version: '3.8'

services:
  web:
    build:
      context: ./isu  # Указываем путь к папке, где находится Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./isu:/app  # Монтируем папку isu в контейнер
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: