# Generated by Django 5.2 on 2025-04-14 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_role_options_alter_role_name_vacancy'),
    ]

    operations = [
    ]
